version: "3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    # ports:
    #   - 9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  data:

networks:
  default:
    external: true
    name: webproxy