version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    environment:
      - DOCKER_APP_DIR=${DOCKER_APP_DIR}
    # ports:
    #   - "8081"
    volumes:
      - ${DOCKER_APP_DIR}/metube:/downloads
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  default:
    external: true
    name: webproxy